//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FETrainingModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public System.Guid UserId { get; set; }
        public string ProjectId { get; set; }
        public string Name { get; set; }
        public string Goal { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<byte> Process { get; set; }
        public Nullable<byte> TrainVal { get; set; }
        public Nullable<byte> ValidVal { get; set; }
        public Nullable<byte> TestVal { get; set; }
        public string Model { get; set; }
    }
}
